name: Pipeline CD
on: [push, pull_request]
jobs:
  pipeline_cd:
    name: "Default CD pipeline"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: '100s'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: set crdential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Run gcloud
        run: gcloud run services list
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'hello-cloud-run'
          #image: 'us-docker.pkg.dev/cloudrun/container/hello:latest'
          image: 'europe-west9-docker.pkg.dev/ambient-net-377313/demo-repo/my-sephora-cicd-demo:1.0'
          region: 'europe-west9'
          flags: '--allow-unauthenticated'
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
